chore: Use Listr to describe tasks

diff --git a/docker/step b/docker/step
--- a/docker/step
+++ b/docker/step
@@ -24,10 +24,10 @@ done
 command -v shell-quote >/dev/null 2>&1 && quoted_command=$(shell-quote "$@") || quoted_command="${@@Q}"
 
 if [ -n "$PRETTY" ]; then
-    echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m \e[34m<\e[39m "
-    echo "$quoted_command"
+    echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m "
+    echo "$quoted_command [started]"
 else
-    echo "$(date +%H:%M:%S) < $quoted_command"
+    echo "$(date +%H:%M:%S) $quoted_command [started]"
 fi
 
 if [ "$QUIET" = y ]; then
@@ -51,16 +51,20 @@ fi
 
 if [ $status -eq 0 ]; then
     if [ -n "$PRETTY" ]; then
-        echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m \e[32m>\e[39m "
-        echo "$quoted_command"
+        echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m "
+        echo "$quoted_command [completed]"
     else
-        echo "$(date +%H:%M:%S) > $quoted_command"
+        echo "$(date +%H:%M:%S) $quoted_command [completed]"
     fi
 else
     if [ -n "$PRETTY" ]; then
-        echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m \e[31mx\e[39m "
-        echo "$quoted_command ($status)"
+        echo -ne "\e[90m[$(date +%H:%M:%S)]\e[39m "
+        echo "$quoted_command [failed]"
+        echo -e "\e[90m[$(date +%H:%M:%S)]\e[39m Command failed with exit code $status"
     else
-        echo "$(date +%H:%M:%S) x $quoted_command"
+        echo "$(date +%H:%M:%S) $quoted_command [failed]"
+        echo "[$(date +%H:%M:%S)] Command failed with exit code $status"
     fi
 fi
+
+exit $status
